config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'dashboard#index'
  
  

  resources :sales do
    resources :sale_details
  end

  resources :items
  resources :units
  resources :towns
  resources :categories
  resources :brands

  #get 'validate_suggested_brand/index'
  get '/brands_suggestion', to: 'brands_suggestion#index'
  get '/validate_suggested_brand', to: 'validate_suggested_brand#index'


  #get 'validate_suggested_item/index'
  get '/items_suggestion', to: 'items_suggestion#index'
  get '/validate_suggested_item', to: 'validate_suggested_item#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sale.rb
# == Schema Information
#
# Table name: sales
#
#  id         :integer          not null, primary key
#  number     :integer
#  date       :date
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  state      :integer
#  user_id    :integer
#

class Sale < ApplicationRecord
	has_many :sale_details, inverse_of: :sale, dependent: :destroy
	has_many :items, through: :sale_details
	belongs_to :user

	validates :number, presence: true
	validates :date, presence: true

	accepts_nested_attributes_for :sale_details, reject_if: :sale_detail_rejectable?,
									allow_destroy: true

	enum state: [:draft, :confirmed]

	def total
		details = self.sale_details

		total = 0.0
		details.flat_map do |d|
			total += d.qty * d.price
		end
		total
	end

	private

		def sale_detail_rejectable?(att)
			att[:item_id].blank? || att[:qty].blank? || att[:price].blank? || att[:qty].to_f <= 0 || att[:price].to_f <= 0
		end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:create, :show, :edit, :update, :destroy]
  PAGE_SIZE = 10

  # GET /sales
  # GET /sales.json
  def index
    # clear no saved sales:
    unsaved_sales = Sale.where(state: "draft", user: current_user)
    unsaved_sales.each do |sale|
      sale.destroy
    end

    @page = (params[:page] || 0).to_i
    @keywords = params[:keywords]

    search = Search.new(@page, PAGE_SIZE, @keywords, current_user)
    @sales, @number_of_pages = search.sales
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    last_sale = Sale.where(state: "confirmed", user: current_user).maximum('number')
    number =  (last_sale != nil) ? last_sale + 1 : 1
    @sale = Sale.create(date: Date::current, number: number, state: "draft", user: current_user)
    @sale.sale_details.build
    params[:sale_id] = @sale.id.to_s
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    @sale.confirmed!
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to sales_url, notice: 'Venta actualizada.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Venta eliminada.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:number, :date, sale_details_attributes: [:id, :sale_id, :item_id, :number, :qty, :price, :_destroy] )
    end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_form.html.erb
<div class="container-fluid" id="sale-form">
  <div class="row">

    <div class="panel-body">
      <%= form_for(@sale) do |f| %>
        <% if @sale.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

            <ul>
            <% @sale.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="row">
          <div class="col-xs-5 col-md-4">
            <div class="form-group">
              <div class="col-xs-6 col-md-4 text-left">
                <%= f.label :number, "Número" %>
              </div>
              <div class="col-xs-6 col-md-4">
                <%= f.text_field :number, placeholder: "Número", class: "form-control" %>
              </div>
            </div>
          </div>
          <div class="col-xs-6 col-xs-offset-1 col-md-4 col-md-offset-4">
            <div class="form-group">
              <div class="col-xs-4 col-md-4 text-right">
                <%= f.label :date, "Fecha" %>
              </div>
              <div class="col-xs-8 col-md-6 text-right">
                <%= f.date_field :date, placeholder: "Fecha", class: "form-control" %>
              </div>
            </div>
          </div>
        </div>
        <hr>
        <br>
        <div class="panel-body" id="sale-details">
          <%= (@sale.sale_details.count > 0) ? render(partial: 'table', locals: { sale: @sale, show_actions: true }) : 'No hay detalles cargados' %>
        </div>
        <div class="row">
          <div class="col-xs-2 col-xs-offset-5 text-center">
            <%= link_to "Nuevo detalle", new_sale_sale_detail_path(sale_id: @sale.id), remote: true, class: "btn btn-info" %>
          </div>
        </div>
        <br>
        <% message = (action_name == 'edit') ? "Volver" : "Aceptar" %>
        <%= f.submit message, class: "btn btn-success" %>
      <% end %>
      <div class="modal fade" id="new-detail-modal" title="Modal"></div>
    </div>
  </div>
</div>

app/views/sales/_pager.html.erb
<nav>
	<ul class="pager">
		<li class="previous <%= page == 0 ? 'disabled' : '' %>">
			<%= link_to_if page > 0, "&larr; Anterior".html_safe,
						sales_path(keywords: keywords, page: page - 1) %>
		</li>
		<li class="next <%= page == @number_of_pages ? 'disabled' : '' %>">
			<%= link_to_if page < @number_of_pages, "Siguiente &rarr;".html_safe,
						sales_path(keywords: keywords, page: page + 1) %>
		</li>
	</ul>
</nav>

app/views/sales/_results_search.html.erb
<table class="table">
  <thead>
    <tr>
      <%= render partial: "pager", locals: { keywords: @keywords, page: @page } %>
    </tr>
    <tr>
      <th></th>
      <th>Número</th>
      <th>Fecha</th>
      <th>Total</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td>
          <%= button_to sale_path(sale), {method: :get, class: "btn btn-info"} do %>
            <span class="glyphicon glyphicon-eye-open" aria-hidden="true"> </span> Ver
          <% end %>
        </td>
        <td><%= sale.number %></td>
        <td><%= sale.date.strftime("%d/%m/%Y") %></td>
        <td><%= number_to_currency(sale.total) %></td>
        <td>
          <%= button_to edit_sale_path(sale), {method: :get, class: "btn btn-info"} do %>
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"> </span> Editar
          <% end %>
        </td>
        <td>
          <%= button_to sale, { method: :delete, data: { confirm: '¿Está seguro?' }, class: "btn btn-danger" } do %>
            <span class="glyphicon glyphicon-trash" aria-hidden="true"> </span> Eliminar
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sales/_sale_detail_fields.html.erb
<%= form_for :sale_details do |f| %>
  <div class="nested-fields row">
    <div class="col-xs-5">
      <div class="form-group">
          <%= f.label :item_id, class: "sr-only" %>
          <%= f.text_field :item, autofocus: true, placeholder: "Artículo", class: "form-control" %>
          <%= f.hidden_field :item_id %>
      </div>
    </div>
    <div class="col-xs-2">
      <div class="form-group">
          <%= f.label :qty, class: "sr-only" %>
          <%= f.text_field :qty, placeholder: "Cant.", class: "form-control" %>
      </div>
    </div>
    <div class="col-xs-2">
      <div class="form-group">
          <%= f.label :price, class: "sr-only" %>
          <%= f.text_field :price, placeholder: "Precio", class: "form-control" %>
      </div>
    </div>
    <div class="col-xs-2">
      <div class="form-group">
          <%= f.label :subtotal, class: "sr-only" %>
          <%= f.text_field :subtotal, placeholder: "0", class: "form-control", disabled: true %>
      </div>
    </div>
  </div>
  <%= f.submit "Aceptar", class: "btn btn-success", "data-dismiss": "modal" %>
<% end %>

app/views/sales/_table.html.erb
<% show_actions = show_actions.nil? ? false : show_actions %>

<div class="table-responsive">
	<table class="table table-condensed">
		<thead>
            <tr>
				<td><strong>Nº</strong></td>
				<td><strong>Descripción</strong></td>
				<td class="text-right"><strong>Cantidad</strong></td>
				<td class="text-right"><strong>Precio</strong></td>
				<td class="text-right"><strong>Subtotal</strong></td>
				<%= show_actions ? '<td colspan="2"></td>'.html_safe : "" %> 
            </tr>
		</thead>
		<tbody>
			<div id="sale-details-index">
				<%= render partial: "sale_details/index", locals: {show_actions: show_actions} %>
			</div>
			<tr>
				<td class="thick-line"></td>
				<td class="thick-line"></td>
				<td class="thick-line"></td>
				<td class="thick-line text-right"><h3>Total</h3></td>
				<td class="thick-line text-right"><h3><%= number_to_currency(sale.total) %></h3></td>
				<%= show_actions ? '<td colspan="2" class=""></td>'.html_safe : "" %> 
			</tr>
		</tbody>
	</table>
</div>

app/views/sales/edit.html.erb
<div class="container-fluid">
	<div class="row">
		<h1>Editar Venta</h1>

		<%= render 'form', sale: @sale %>

	</div>
</div>

app/views/sales/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Ventas</div>
  <div class="panel-body">
    <%= render partial: 'layouts/search_form', locals: { search_entity: 'sales', word: "Venta" } %>
    <br>
    <div class="col-md-5 col-md-offset-5 col-sm-5 col-sm-offset-5">
      <p>
        <%= button_to new_sale_path, {method: :get, class: "btn btn-success"} do %>
          <span class="glyphicon glyphicon-plus" aria-hidden="true"> </span> Nueva Venta
        <% end %>
      </p>
    </div>
  </div>
  <%= render partial: 'results_search' %>
</div>

app/views/sales/new.html.erb
<div class="container-fluid">
	<div class="row">
		<h1>Nueva Venta</h1>

		<%= render 'form', sale: @sale %>

		<%= link_to 'Volver', sales_path, data: { confirm: "Se perderán los cambios ¿Está seguro?" } %>
	</div>
</div>

app/views/sales/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-12">
    		<div class="invoice-title">
    			<h2>Venta</h2>
    			<h3 class="pull-right">Número # <%= @sale.number %></h3>
    		</div>
    		<hr>
    		<div class="row">
    			<div class="col-xs-6">
    			</div>
    			<div class="col-xs-6 text-right">
    				<address>
    					<strong>Fecha:</strong><br>
    					<%= @sale.date.strftime("%d/%m/%Y") %><br><br>
    				</address>
    			</div>
    		</div>
    		<div class="row">
		    	<div class="col-md-12">
		    		<div class="panel panel-default">
		    			<div class="panel-heading">
		    				<h3 class="panel-title"><strong>Detalles de Venta</strong></h3>
		    			</div>
		    			<div class="panel-body">
		    				<%= render partial: 'table', locals: { sale: @sale } %>
		    			</div>
		    		</div>
		    	</div>
		    </div>
    	</div>
    </div>
</div>

<%= link_to 'Volver', sales_path %>